steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orvio-pulse:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orvio-pulse:$COMMIT_SHA",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "orvio-pulse"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orvio-pulse:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--min-instances=0"
      - "--max-instances=3"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--concurrency=80"
      - "--set-env-vars=APP_MODE=demo,FIREBASE_PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=${_REGION}"
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orvio-pulse:$COMMIT_SHA"
substitutions:
  _REGION: asia-south1
  _REPOSITORY: orvio
options:
  logging: CLOUD_LOGGING_ONLY
